### ISSUE TITLE
cannot run 

### ISSUE THREAD

**Issue by jiahengqi** [saket-maheshwary/AutoLearn#1]
```
Traceback (most recent call last):
  File "main.py", line 518, in <module>
    dependent(original_ig_train1, 0.7, 1)
  File "main.py", line 115, in dependent
    a,b=pearsonr(x[:,i][:,np.newaxis],x[:,j][:,np.newaxis])
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/stats.py", line 3410, in pearsonr
    xmean = x.mean(dtype=dtype)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 75, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: No loop matching the specified signature and casting
```

**Comment by MayurTuteja** [comment]
I am facing the same issue @jiahengqi

**Comment by jimmyhartwell** [comment]
I was able to run it with Python 2.7 and following library versions:

```
scikit-learn==0.18
numpy==1.16.6
pandas==0.24.2
scipy==1.2.3
matplotlib==2.2.5
```
